In [1]:
#Q1. What is the relationship between polynomial functions and kernel functions in machine learning
#algorithms?

In [2]:
#The kernel function is what is applied on each data instance to map the original non-linear observations into
#a higher-dimensional space.
#In machine learning, the polynomial kernel is a kernel function commonly used with support vector machines (SVMs)
#and other kernelized models, that represents the similarity of vectors (training samples) in a feature space over
#polynomials of the original variables, allowing learning of non-linear models.

In [3]:
#Q2. How can we implement an SVM with a polynomial kernel in Python using Scikit-learn?

In [4]:
#Importing the necessary libraries.
#import numpy as np.
#from sklearn. datasets import load_digits.
#from sklearn. model_selection import train_test_split.
#from sklearn. svm import SVC.
#from sklearn.
# Importing the dataset from the sklearn library into a local variable called dataset.

In [5]:
#Q3. How does increasing the value of epsilon affect the number of support vectors in SVR?

In [6]:
#Parameter ε controls the width of the ε-insensitive zone, used to fit the training data. The value of ε can 
#affect the number of support vectors used to construct the regression function. The bigger ε, the fewer support
#vectors are selected. On the other hand, bigger ε-values results in more flat estimates.

In [7]:
#Q4. How does the choice of kernel function, C parameter, epsilon parameter, and gamma parameter
#affect the performance of Support Vector Regression (SVR)? Can you explain how each parameter works
#and provide examples of when you might want to increase or decrease its value?

In [8]:
#The linear kernel is mostly preferred for text classification problems as it performs well for large datasets.
#Gaussian kernels tend to give good results when there is no additional information regarding data that is not
#available.
#One can tune the SVM by changing the parameters \(C, \gamma\) and the kernel function. The function for tuning 
#the parameters available in scikit-learn is called gridSearchCV(). Parameters of this function are defined 
#as: estimator: It is the estimator object which is svm.
#we use the following hyperparameter values for the SVR model: epsilon = 10, C = 1. As explained before, epsilon
#defines the width of the tube around the hyperplane. Meanwhile, regularization parameter C allows us to assign the
#weight to “slack,” telling the algorithm how much we care about the error.
#One can tune the SVM by changing the parameters \(C, \gamma\) and the kernel function. The function for tuning 
#the parameters available in scikit-learn is called gridSearchCV(). Parameters of this function are defined 
#as: estimator: It is the estimator object which is svm.

In [9]:
#Q5. Assignment:

In [10]:
#QImport the necessary libraries and load the dataseg

In [11]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [113]:
#Q Import the necessary libraries and load the dataseg

In [114]:
from sklearn.datasets import load_iris

In [115]:
data = load_iris()

In [116]:
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [117]:
#Q .Split the dataset into training and testing setZ

In [118]:
x=pd.DataFrame(data.data,columns=data.feature_names)
y=data.target

In [119]:
from sklearn.model_selection import train_test_split

In [120]:
 x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.25,random_state=42)

In [121]:
x_train,x_test

(     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
 4                  5.0               3.6                1.4               0.2
 32                 5.2               4.1                1.5               0.1
 142                5.8               2.7                5.1               1.9
 85                 6.0               3.4                4.5               1.6
 86                 6.7               3.1                4.7               1.5
 ..                 ...               ...                ...               ...
 71                 6.1               2.8                4.0               1.3
 106                4.9               2.5                4.5               1.7
 14                 5.8               4.0                1.2               0.2
 92                 5.8               2.6                4.0               1.2
 102                7.1               3.0                5.9               2.1
 
 [112 rows x 4 columns],
      sepal length (cm)  

In [122]:
#Q. Preprocess the data using any technique of your choice (e.g. scaling, normaliMationK

In [123]:
from sklearn.preprocessing import StandardScaler

In [124]:
scaler =StandardScaler()

In [127]:
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [128]:
x_test_scaled

array([[ 0.33066442, -0.55192639,  0.51683569, -0.01918559],
       [-0.15985763,  1.7460571 , -1.21973223, -1.22787777],
       [ 2.29275265, -1.01152309,  1.79031883,  1.45810485],
       [ 0.20803391, -0.32212804,  0.4010645 ,  0.3837118 ],
       [ 1.18907802, -0.55192639,  0.57472129,  0.24941267],
       [-0.52774918,  0.8268637 , -1.33550342, -1.09357864],
       [-0.28248815, -0.32212804, -0.11990588,  0.11511354],
       [ 1.31170853,  0.13746866,  0.74837808,  1.45810485],
       [ 0.45329494, -1.93071649,  0.4010645 ,  0.3837118 ],
       [-0.03722712, -0.78172474,  0.05375091, -0.01918559],
       [ 0.82118648,  0.367267  ,  0.74837808,  1.05520746],
       [-1.26353226, -0.09232969, -1.39338902, -1.49647603],
       [-0.40511866,  1.05666205, -1.45127462, -1.3621769 ],
       [-1.14090175,  0.13746866, -1.33550342, -1.49647603],
       [-0.89564072,  1.7460571 , -1.33550342, -1.22787777],
       [ 0.57592545,  0.59706535,  0.51683569,  0.51801093],
       [ 0.82118648, -0.

In [129]:
#Q. Create an instance of the SVC classifier and train it on the training datW

In [130]:
from sklearn.svm import SVC

In [131]:
svc=SVC(kernel='linear')

In [132]:
svc.fit(x_train,y_train)

SVC(kernel='linear')

In [133]:
#Q Use the trained classifier to predict the labels of the testing datW

In [134]:
y_pred=svc.predict(x_test)

In [135]:
y_pred


array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0])

In [136]:
#Q. Evaluate the performance of the classifier using any metric of your choice (e.g. accuracy,
#precision, recall, F1-scoreK

In [137]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [138]:
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      1.00      1.00        11
           2       1.00      1.00      1.00        12

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38

[[15  0  0]
 [ 0 11  0]
 [ 0  0 12]]
1.0


In [139]:
#Q. Tune the hyperparameters of the SVC classifier using GridSearchCV or RandomiMedSearchCV to
#improve its performanc_

In [141]:
from sklearn.model_selection import GridSearchCV
#defining parameter range
param_grid={'C':[0.1,1,10,100,1000],
            'gamma':[1,0.1,0.01,0.001,0.0001]
           }

In [142]:
grid=GridSearchCV(SVC(),param_grid=param_grid,refit=True,cv=5,verbose=3)

In [143]:
grid.fit(x_train,y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END ....................C=0.1, gamma=1;, score=1.000 total time=   0.0s
[CV 2/5] END ....................C=0.1, gamma=1;, score=0.957 total time=   0.0s
[CV 3/5] END ....................C=0.1, gamma=1;, score=0.818 total time=   0.0s
[CV 4/5] END ....................C=0.1, gamma=1;, score=1.000 total time=   0.0s
[CV 5/5] END ....................C=0.1, gamma=1;, score=0.955 total time=   0.0s
[CV 1/5] END ..................C=0.1, gamma=0.1;, score=1.000 total time=   0.0s
[CV 2/5] END ..................C=0.1, gamma=0.1;, score=0.870 total time=   0.0s
[CV 3/5] END ..................C=0.1, gamma=0.1;, score=0.864 total time=   0.0s
[CV 4/5] END ..................C=0.1, gamma=0.1;, score=0.955 total time=   0.0s
[CV 5/5] END ..................C=0.1, gamma=0.1;, score=0.864 total time=   0.0s
[CV 1/5] END .................C=0.1, gamma=0.01;, score=0.348 total time=   0.0s
[CV 2/5] END .................C=0.1, gamma=0.01

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001]},
             verbose=3)